import assert from "node:assert/strict";
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, test } from "node:test";
import Database from "better-sqlite3";
import { startIdempotencyFixture, type FixtureHandle } from "./idempotency-p1-fixture-server.js";
import { IdempotencyAmbiguousError, WriteIdempotencyStore } from "../src/idempotency-store.js";

const repoRoot = join(import.meta.dirname, "..");
const artifactsDir = join(repoRoot, "artifacts");
const reportPath = join(artifactsDir, "idempotency-p1-report.json");
const visualPath = join(artifactsDir, "idempotency-p1-evidence.html");
const secretPatterns = [
  /bearer\s+[A-Za-z0-9._~-]+/i,
  /owner[_-]?token\s*[=:]\s*[^\s,;]+/i,
  /access[_-]?token\s*[=:]\s*[^\s,;]+/i,
  /code[_-]?verifier\s*[=:]\s*[^\s,;]+/i,
];

type TestResult = { id: string; status: "passed" | "failed"; detail: string };
const results: TestResult[] = [];
let fixture: FixtureHandle;
let fixtureRoot: string;

function record(id: string, status: "passed" | "failed", detail: string): void {
  results.push({ id, status, detail });
}

async function post(
  scopeKey: string,
  idempotencyKey: string,
  body: Record<string, unknown>,
  options: { simulateTimeout?: boolean } = {},
): Promise<{ status: number; payload: Record<string, unknown> }> {
  const response = await fetch(`${fixture.url}/write`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-scope-key": scopeKey,
      "x-idempotency-key": idempotencyKey,
      ...(options.simulateTimeout ? { "x-simulate-timeout": "1" } : {}),
    },
    body: JSON.stringify(body),
  });
  return { status: response.status, payload: await response.json() as Record<string, unknown> };
}

async function writeVisualEvidence(): Promise<void> {
  await mkdir(artifactsDir, { recursive: true });
  const passed = results.filter((result) => result.status === "passed").length;
  const rows = results.map((result) => `<tr><td>${result.id}</td><td class="${result.status}">${result.status.toUpperCase()}</td><td>${result.detail}</td></tr>`).join("\n");
  const reportData = {
    suite: "IDEMP-P1-001..008",
    mode: "real HTTP fixture with SQLite transaction store",
    status: passed === 8 && results.length === 8 ? "passed" : "failed",
    passed,
    total: 8,
    effect_count: fixture?.effectCount() ?? null,
    cases: results,
    scenarios: results,
    secret_leak_detected: false,
  };
  const unsignedReport = JSON.stringify(reportData);
  const effectLog = await readFile(fixture.effectLogPath, "utf8");
  reportData.secret_leak_detected = secretPatterns.some((pattern) => pattern.test(`${effectLog}\n${unsignedReport}`));
  const reportText = JSON.stringify(reportData, null, 2) + "\n";
  await writeFile(reportPath, reportText, "utf8");
  await writeFile(visualPath, `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Idempotency P1 Evidence</title>
<style>body{font-family:Arial,sans-serif;background:#071426;color:#f4f8fc;margin:0;padding:48px}h1{font-size:32px}p{color:#a9bacb}.summary{font-size:56px;color:#31d18b;font-weight:700;margin:24px 0}table{border-collapse:collapse;width:100%;max-width:1100px}th,td{border-bottom:1px solid #24445d;text-align:left;padding:14px}th{color:#62d8ff;text-transform:uppercase;font-size:12px;letter-spacing:1px}.passed{color:#31d18b}.failed{color:#f27676}.note{margin-top:28px;color:#8099ac;font-size:13px}</style></head>
<body><p>IDEMP-P1 CONTRACT HARNESS · HTTP + SQLITE</p><h1>Concurrent deduplication and conflict evidence</h1><div class="summary">${passed}/8 passed</div><p>Each scenario was executed against a real local HTTP server backed by SQLite transactions. This fixture validates the proposed contract before wiring it to the production MCP write tool.</p><table><thead><tr><th>ID</th><th>Status</th><th>Observed oracle</th></tr></thead><tbody>${rows}</tbody></table><p class="note">Artifacts: idempotency-p1-report.json · evidence generated by scripts/e2e-idempotency-p1.test.ts</p></body></html>`, "utf8");
}

before(async () => {
  fixtureRoot = await mkdtemp(join(tmpdir(), "devspace-idempotency-p1-"));
  fixture = await startIdempotencyFixture(fixtureRoot);
});

test("IDEMP-P1-001 first write creates exactly one effect", async () => {
  const beforeEffects = fixture.effectCount();
  const result = await post("workspace-a", "key-001", { path: "one.txt", content: "alpha" });
  assert.equal(result.status, 201);
  assert.equal(result.payload.replayed, false);
  assert.equal(fixture.effectCount() - beforeEffects, 1);
  await access(join(fixtureRoot, "one.txt"), fsConstants.F_OK);
  record("IDEMP-P1-001", "passed", "first claim succeeded and created one file effect");
});

test("IDEMP-P1-002 replay returns the stored result without a second effect", async () => {
  const beforeEffects = fixture.effectCount();
  const result = await post("workspace-a", "key-001", { path: "one.txt", content: "alpha" });
  assert.equal(result.status, 200);
  assert.equal(result.payload.replayed, true);
  assert.equal(fixture.effectCount(), beforeEffects);
  record("IDEMP-P1-002", "passed", "same key and canonical payload replayed persisted result");
});

test("IDEMP-P1-003 same key with different payload returns conflict", async () => {
  const beforeEffects = fixture.effectCount();
  const result = await post("workspace-a", "key-001", { path: "one.txt", content: "different" });
  assert.equal(result.status, 409);
  assert.equal(result.payload.error, "idempotency_conflict");
  assert.equal(fixture.effectCount(), beforeEffects);
  record("IDEMP-P1-003", "passed", "payload hash mismatch returned 409 without effect");
});

test("IDEMP-P1-004 concurrent claims deduplicate atomically", async () => {
  const beforeEffects = fixture.effectCount();
  const body = { path: "concurrent.txt", content: "one effect", delayMs: 80 };
  const [left, right] = await Promise.all([
    post("workspace-a", "key-004", body),
    post("workspace-a", "key-004", body),
  ]);
  assert.deepEqual([left.status, right.status].sort((a, b) => a - b), [201, 409]);
  assert.equal(fixture.effectCount() - beforeEffects, 1);
  const replay = await post("workspace-a", "key-004", body);
  assert.equal(replay.status, 200);
  assert.equal(replay.payload.replayed, true);
  record("IDEMP-P1-004", "passed", "two concurrent requests produced one owner and one pending response");
});

test("IDEMP-P1-005 retry after ambiguous timeout replays the committed result", async () => {
  const beforeEffects = fixture.effectCount();
  await assert.rejects(post("workspace-a", "key-005", { path: "timeout.txt", content: "committed" }, { simulateTimeout: true }));
  const retry = await post("workspace-a", "key-005", { path: "timeout.txt", content: "committed" });
  assert.equal(retry.status, 200);
  assert.equal(retry.payload.replayed, true);
  assert.equal(fixture.effectCount() - beforeEffects, 1);
  record("IDEMP-P1-005", "passed", "lost response was recovered by replay without duplicate write");
  const recoveryRoot = await mkdtemp(join(tmpdir(), "devspace-idempotency-ambiguous-"));
  const recoveryDatabase = new Database(join(recoveryRoot, "recovery.sqlite"));
  const recoveryStore = new WriteIdempotencyStore(recoveryDatabase);
  let releaseRecoveryEffect = () => undefined;
  const recoveryGate = new Promise<void>((resolve) => { releaseRecoveryEffect = resolve; });
  const ownerPromise = recoveryStore.run("workspace-recovery", "key-ambiguous", { value: "uncertain" }, async () => {
    await recoveryGate;
    return { effect: "committed-after-reconciliation" };
  }, { now: new Date("2026-08-16T00:00:00.000Z"), pendingLeaseMs: 1_000 });
  try {
    await assert.rejects(
      recoveryStore.run("workspace-recovery", "key-ambiguous", { value: "uncertain" }, () => ({ effect: "duplicate" }), { now: new Date("2026-08-16T00:00:02.000Z"), pendingLeaseMs: 1_000 }),
      (error) => error instanceof IdempotencyAmbiguousError && error.code === "IDEMPOTENCY_REQUEST_AMBIGUOUS",
    );
  } finally {
    releaseRecoveryEffect();
    await ownerPromise;
    recoveryDatabase.close();
    await rm(recoveryRoot, { recursive: true, force: true });
  }
  results[results.length - 1].detail = "lost response replays committed result; expired lease is surfaced as ambiguous without automatic re-execution";
});

test("IDEMP-P1-006 identical keys are isolated by scope", async () => {
  const beforeEffects = fixture.effectCount();
  const left = await post("workspace-a", "same-key", { path: "scope-a.txt", content: "a" });
  const right = await post("workspace-b", "same-key", { path: "scope-b.txt", content: "b" });
  assert.equal(left.status, 201);
  assert.equal(right.status, 201);
  assert.equal(fixture.effectCount() - beforeEffects, 2);
  record("IDEMP-P1-006", "passed", "same key in different scopes produced independent effects");
});

test("IDEMP-P1-007 retention expiry is explicit and deterministic", async () => {
  const root = await mkdtemp(join(tmpdir(), "devspace-idempotency-retention-"));
  const database = new Database(join(root, "retention.sqlite"));
  const store = new WriteIdempotencyStore(database);
  const t0 = new Date("2026-08-16T00:00:00.000Z");
  let effects = 0;
  try {
    await store.run("workspace-retention", "key-007", { value: "first" }, () => ({ effect: ++effects }), { now: t0, retentionMs: 1_000 });
    assert.equal(store.pruneExpired(new Date("2026-08-16T00:00:02.000Z")), 1);
    await store.run("workspace-retention", "key-007", { value: "second" }, () => ({ effect: ++effects }), { now: new Date("2026-08-16T00:00:02.000Z"), retentionMs: 1_000 });
    assert.equal(effects, 2);
    record("IDEMP-P1-007", "passed", "retention expiry removed only completed record and accepted a new explicit intent");
  } finally {
    database.close();
    await rm(root, { recursive: true, force: true });
  }
});

test("IDEMP-P1-008 artifacts and logs contain no secret-like values", async () => {
  const effectLog = await readFile(fixture.effectLogPath, "utf8");
  const report = JSON.stringify(results);
  for (const pattern of secretPatterns) {
    assert.doesNotMatch(effectLog, pattern);
    assert.doesNotMatch(report, pattern);
  }
  record("IDEMP-P1-008", "passed", "fixture effect log and test evidence passed the secret scan");
  await writeVisualEvidence();
  const reportArtifact = await readFile(reportPath, "utf8");
  const visualArtifact = await readFile(visualPath, "utf8");
  for (const pattern of secretPatterns) {
    assert.doesNotMatch(reportArtifact, pattern);
    assert.doesNotMatch(visualArtifact, pattern);
  }
});

after(async () => {
  try {
    await writeVisualEvidence();
  } finally {
    await fixture?.close();
    await rm(fixtureRoot, { recursive: true, force: true });
  }
});
